# Autogenerated wrapper script for teensy_loader_cli_jll for aarch64-linux-gnu
export teensy_loader_cli

JLLWrappers.@generate_wrapper_header("teensy_loader_cli")
JLLWrappers.@declare_executable_product(teensy_loader_cli)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        teensy_loader_cli,
        "bin/teensy_loader_cli",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
